# MIT 18.06 Linear Algebra — Lecture 4
## Inverses, Transposes, and Factorizations
Instructor: Gilbert Strang

In this lecture, we deepen our understanding of matrix inverses and connect them
to matrix multiplication, transposes, and elimination.

The focus is not on computing inverses by formulas, but on understanding how
inverse operations behave when matrices are combined and factorized.

Key themes of this lecture include:
- How the inverse of a product of matrices works
- Why the order of multiplication reverses when taking inverses
- The relationship between inverse and transpose
- How elimination matrices lead naturally to LU factorization
- How multipliers from elimination are stored in the matrix L
- Why row exchanges introduce permutation matrices
- The computational cost of elimination and matrix operations

This lecture shows that inverses, transposes, and factorizations are not
separate topics, but different views of the same underlying structure.


## Section 1 — Inverse of a Product

When two matrices are multiplied, the result represents a composition of
two linear transformations.

If matrix B is applied first and matrix A is applied second, the product
AB represents this combined action.

Taking the inverse of a product means undoing both transformations.
However, undoing must happen in the reverse order.

This leads to a fundamental rule:

- The inverse of AB is not A_inv B_inv
- The inverse of AB is B_inv A_inv

In words:
To undo A followed by B, we must undo B first, then undo A.

This rule reflects the idea that matrix multiplication represents
composition of actions, and inverses reverse those actions.


In [1]:
import numpy as np
A = np.array([
    [1, 2],
    [0, 1]
])

B = np.array([
    [1, 0],
    [3, 1]
])

AB = A @ B
print("AB = \n", AB)

AB = 
 [[7 2]
 [3 1]]


In [2]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)

AB_inv = B_inv @ A_inv
print("AB_inv = \n", AB_inv)

AB_inv = 
 [[ 1. -2.]
 [-3.  7.]]


In [3]:
I_1 = AB @ AB_inv # (A.B).(B_inv.A_inv)
I_2 = AB @ AB_inv # (B_inv.A_inv)(A.B)

print("I_1: ", I_1)
print("I_2: ", I_2)

I_1:  [[1. 0.]
 [0. 1.]]
I_2:  [[1. 0.]
 [0. 1.]]


## Section 2 — Transpose and Inverse

The transpose of a matrix swaps rows and columns.

While the inverse undoes a transformation, the transpose changes how
the transformation is represented, switching the roles of rows and columns.

A key result is that inverse and transpose interact in a clean way.

Taking the inverse and taking the transpose both reverse order.
As a result, they work naturally together.

This leads to the identity:
- The inverse of the transpose of a matrix is the transpose of its inverse.

In this section, we verify this relationship numerically and interpret
what it means geometrically.


In [5]:
A = np.array([
    [2, 1],
    [1, 1]
])
print("A = \n", A)

A_inv = np.linalg.inv(A)
print("A_inv = \n", A_inv)

AT = np.linalg.matrix_transpose(A)
print("AT = \n", AT)

A_inv_T = np.linalg.matrix_transpose(A_inv)
print("A_inv_T = \n", A_inv_T)

A = 
 [[2 1]
 [1 1]]
A_inv = 
 [[ 1. -1.]
 [-1.  2.]]
AT = 
 [[2 1]
 [1 1]]
A_inv_T = 
 [[ 1. -1.]
 [-1.  2.]]


In [6]:
I_1 = AT @ A_inv_T
print("I_1 = \n", I_1)

I_2 = A_inv_T @ AT
print("I_2 = \n", I_2)

I_1 = 
 [[1. 0.]
 [0. 1.]]
I_2 = 
 [[1. 0.]
 [0. 1.]]


## Section 3 — Elimination Matrices and LU Factorization

Gaussian elimination transforms a matrix into an upper triangular form.

Each elimination step can be represented by an elimination matrix.
Multiplying these elimination matrices produces the upper triangular matrix U.

If no row exchanges are required, the original matrix A can be factored as:

A = L U

Here:
- U is the result of elimination
- L contains the elimination multipliers
- L is the inverse of the product of elimination matrices

This factorization shows that elimination is not just a procedure,
but a matrix decomposition with clear structure.


In [9]:
A = np.array([
    [2, 1],
    [8, 7]
])
print("A = \n", A)

E_2_1 = np.array([
    [1, 0],
    [-4, 1]
])
print("E_2_1 = \n", E_2_1)

U = E_2_1 @ A
print("U = \n", U)

L = np.array([
    [1, 0],
    [4, 1]
])
print("L = \n", L)

#A = LU
A_back = L @ U
print("A_back = \n", A_back)

A = 
 [[2 1]
 [8 7]]
E_2_1 = 
 [[ 1  0]
 [-4  1]]
U = 
 [[2 1]
 [0 3]]
L = 
 [[1 0]
 [4 1]]
A_back = 
 [[2 1]
 [8 7]]


## LU Factorization in the 3×3 Case (No Row Exchanges)

In the 2×2 case, LU factorization required a single elimination step.
In the 3×3 case, elimination happens in multiple stages.

Each stage removes entries below a pivot using an elimination matrix.
The product of these elimination matrices transforms A into an upper
triangular matrix U.

If no row exchanges are required, the process has a simple structure:

- Successive elimination matrices E act on A to produce U
- The inverses of these elimination matrices combine to form L
- All elimination multipliers appear directly in L

Symbolically:
E3,2 · E3,1 · E2,1 · A = U
A = L U

where:
- U is upper triangular
- L is lower triangular with ones on the diagonal
- L stores the elimination multipliers

This example demonstrates how LU factorization generalizes naturally
from 2×2 to 3×3 matrices.

## Step 1 — First Elimination Matrix (E2,1)

The first pivot is the top-left entry of the matrix A.

The goal of the first elimination step is to remove the entry directly
below this pivot, without changing the pivot row.

This is done using an elimination matrix E2,1, which subtracts a
multiple of the first row from the second row.

At this stage, only one entry is eliminated.
All other rows remain unchanged.


In [10]:
A = np.array([
    [2, 1, 1],
    [4, 3, 3],
    [8,7 , 9]
])
print("A = \n", A)

E_2_1 = np.array([
    [1, 0, 0],
    [-2, 1, 0],
    [0, 0, 1]
])
print("E_2_1 = \n", E_2_1)

A1 = E_2_1 @ A
print("A1 = \n", A1)

A = 
 [[2 1 1]
 [4 3 3]
 [8 7 9]]
E_2_1 = 
 [[ 1  0  0]
 [-2  1  0]
 [ 0  0  1]]
A1 = 
 [[2 1 1]
 [0 1 1]
 [8 7 9]]


## Step 2 — Eliminate Entry Below the First Pivot (E3,1)

After the first elimination step, the first pivot remains unchanged.
The next goal is to eliminate the entry below the first pivot in the third row.

This step removes the x-entry in row 3 by subtracting a multiple of row 1.

Only one entry is eliminated in this step.
All other rows remain unchanged.


In [12]:
E_3_1 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [-4, 0, 1]
])
print("E_3_1 = \n", E_3_1)

A2 = E_3_1 @ A1
print("A2 = \n", A2)

E_3_1 = 
 [[ 1  0  0]
 [ 0  1  0]
 [-4  0  1]]
A2 = 
 [[2 1 1]
 [0 1 1]
 [0 3 5]]


## Step 3 — Eliminate Entry Below the Second Pivot (E3,2)

After eliminating entries below the first pivot, we move to the second pivot.

The second pivot is located in row 2, column 2.
The goal of this step is to eliminate the entry below this pivot in row 3.

This is the final elimination step needed to produce an upper triangular
matrix U.


In [13]:
E_3_2 = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, -3, 1]
])
print("E_3_2 = \n", E_3_2)

U = E_3_2 @ A2
print("U = \n", U)

E_3_2 = 
 [[ 1  0  0]
 [ 0  1  0]
 [ 0 -3  1]]
U = 
 [[2 1 1]
 [0 1 1]
 [0 0 2]]


## Building the L Matrix from Elimination Multipliers

During elimination, entries below the pivots are removed using row operations.
Each row operation uses a multiplier.

These multipliers do not disappear.
Instead, they are stored in the matrix L.

For LU factorization without row exchanges:
- U contains the final result of elimination
- L contains the multipliers used during elimination
- L is lower triangular with ones on the diagonal

The matrix L is formed by placing each elimination multiplier
in the corresponding position below the diagonal.


In [15]:
L = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [4, 3, 1]
])
print("L = \n", L)

A_back = L @ U
print("A_back = \n", A_back)

L = 
 [[1 0 0]
 [2 1 0]
 [4 3 1]]
A_back = 
 [[2 1 1]
 [4 3 3]
 [8 7 9]]


## Section 6 — Cost of Elimination

Gaussian elimination is an algorithm, and like all algorithms, it has a cost.

For an n×n matrix:
- elimination requires on the order of n³ operations
- more precisely, about (2/3) n³ arithmetic operations

This cost comes from:
- eliminating entries below each pivot
- working on progressively smaller submatrices

Key consequences:
- Computing an inverse is expensive
- Solving Ax = b by elimination is expensive
- LU factorization is valuable because it allows reuse

Once A = LU is computed:
- solving Ax = b requires only forward and back substitution
- this costs on the order of n² operations

## Where the Cost of Elimination Comes From

The cost of Gaussian elimination comes from repeatedly eliminating entries
below each pivot.

To understand the total cost, we count how many arithmetic operations
(additions and multiplications) are performed.

### Step 1 — What happens at the first pivot

For an n×n matrix, the first pivot is in the first row.

To eliminate entries below this pivot:
- We eliminate (n − 1) rows
- Each elimination updates roughly (n − 1) entries in the row

So the first pivot costs on the order of:
(n − 1) × (n − 1) operations

This is approximately n² operations.

---

### Step 2 — What happens at the second pivot

After the first elimination:
- The remaining submatrix is of size (n − 1) × (n − 1)

At the second pivot:
- We eliminate (n − 2) rows
- Each row update touches (n − 2) entries

Cost at this stage:
(n − 2) × (n − 2) ≈ (n − 1)² operations

---

### Step 3 — Continue for all pivots

This process continues until the last pivot.

The total number of operations is approximately:

n² + (n − 1)² + (n − 2)² + ... + 1²

---

### Step 4 — Estimating the total cost

The sum of squares:
1² + 2² + 3² + ... + n²

grows proportionally to n³.

More precisely:
- The sum is approximately (1/3) n³
- Accounting for both multiplication and subtraction leads to about (2/3) n³ operations

---

### Final conclusion

Gaussian elimination on an n×n matrix requires on the order of n³ operations.

This explains why:
- Elimination is expensive for large matrices
- Computing an inverse is costly
- LU factorization is valuable because it allows reuse

Once A = LU is computed:
- Solving Ax = b requires only forward and back substitution
- This costs on the order of n² operations

This dramatic difference in cost is why LU factorization is used in practice.
